todos:
  data:
    initialize: true

site:
  author: 스프링러너
  description: what're your plans today?

logging:
  level:
    todoapp: debug
    org.springframework.beans: debug
    org.springframework.web: trace


